/*
 * GamePlayHandler.h
 *
 * Created: 2025-04-02 4:43:41 PM
 *  Author: mattm
 */ 


#ifndef GAMEPLAYHANDLER_H_
#define GAMEPLAYHANDLER_H_

#include <stdint.h>

#include "config.h"
#include <avr/io.h>
#include <util/delay.h>
#include <avr/interrupt.h>

#define TOPLEFTBLUEPORT &PORTD
#define MIDDLELEFTBLUEPORT &PORTD
#define BOTTOMLEFTBLUEPORT &PORTD
#define TOPMIDDLEBLUEPORT &PORTD
#define TOPRIGHTBLUEPORT &PORTD
#define MIDDLEMIDDLEBLUEPORT &PORTD
#define BOTTOMMIDDLEBLUEPORT &PORTC
#define MIDDLERIGHTBLUEPORT &PORTC
#define BOTTOMRIGHTBLUEPORT &PORTB

#define TOPLEFTYELLOWPORT &PORTC
#define MIDDLELEFTYELLOWPORT &PORTD
#define BOTTOMLEFTYELLOWPORT &PORTD
#define TOPMIDDLEYELLOWPORT &PORTD
#define TOPRIGHTYELLOWPORT &PORTD
#define MIDDLEMIDDLEYELLOWPORT &PORTD
#define BOTTOMMIDDLEYELLOWPORT &PORTD
#define MIDDLERIGHTYELLOWPORT &PORTD
#define BOTTOMRIGHTYELLOWPORT &PORTD

#define TOPLEFTBLUEDDPORT &DDRD
#define MIDDLELEFTBLUEDDPORT &DDRD
#define BOTTOMLEFTBLUEDDPORT &DDRD
#define TOPMIDDLEBLUEDDPORT &DDRD
#define TOPRIGHTBLUEDDPORT &DDRD
#define MIDDLEMIDDLEBLUEDDPORT &DDRD
#define BOTTOMMIDDLEBLUEDDPORT &DDRC
#define MIDDLERIGHTBLUEDDPORT &DDRC
#define BOTTOMRIGHTBLUEDDPORT &DDRB

#define TOPLEFTYELLOWDDPORT &DDRC
#define MIDDLELEFTYELLOWDDPORT &DDRD
#define BOTTOMLEFTYELLOWDDPORT &DDRD
#define TOPMIDDLEYELLOWDDPORT &DDRD
#define TOPRIGHTYELLOWDDPORT &DDRD
#define MIDDLEMIDDLEYELLOWDDPORT &DDRD
#define BOTTOMMIDDLEYELLOWDDPORT &DDRD
#define MIDDLERIGHTYELLOWDDPORT &DDRD
#define BOTTOMRIGHTYELLOWDDPORT &DDRD	

#define TOPLEFTBLUEPIN 0
#define MIDDLELEFTBLUEPIN 1
#define BOTTOMLEFTBLUEPIN 4
#define TOPMIDDLEBLUEPIN 5
#define TOPRIGHTBLUEPIN 6
#define MIDDLEMIDDLEBLUEPIN 7
#define BOTTOMMIDDLEBLUEPIN 4
#define MIDDLERIGHTBLUEPIN 5
#define BOTTOMRIGHTBLUEPIN 0

#define TOPLEFTYELLOWPIN 3
#define MIDDLELEFTYELLOWPIN 2
#define BOTTOMLEFTYELLOWPIN 3
#define TOPMIDDLEYELLOWPIN 0
#define TOPRIGHTYELLOWPIN 1
#define MIDDLEMIDDLEYELLOWPIN 4
#define BOTTOMMIDDLEYELLOWPIN 6
#define MIDDLERIGHTYELLOWPIN 5
#define BOTTOMRIGHTYELLOWPIN 7

#define TOPLEFTBLUEONSHIFT 0
#define MIDDLELEFTBLUEONSHIFT 0
#define BOTTOMLEFTBLUEONSHIFT 0
#define TOPMIDDLEBLUEONSHIFT 0
#define TOPRIGHTBLUEONSHIFT 0
#define MIDDLEMIDDLEBLUEONSHIFT 0
#define BOTTOMMIDDLEBLUEONSHIFT 0
#define MIDDLERIGHTBLUEONSHIFT 0
#define BOTTOMRIGHTBLUEONSHIFT 0

#define TOPLEFTYELLOWONSHIFT 0
#define MIDDLELEFTYELLOWONSHIFT 1
#define BOTTOMLEFTYELLOWONSHIFT 1
#define TOPMIDDLEYELLOWONSHIFT 1
#define TOPRIGHTYELLOWONSHIFT 1
#define MIDDLEMIDDLEYELLOWONSHIFT 1
#define BOTTOMMIDDLEYELLOWONSHIFT 1
#define MIDDLERIGHTYELLOWONSHIFT 1
#define BOTTOMRIGHTYELLOWONSHIFT 1

#define SHIFTREGISTERCLKPORT &PORTC
#define SHIFTREGISTERDATAPORT &PORTB
#define SHIFTREGISTERLATCHPORT &PORTB

#define SHIFTREGISTERCLKDDPORT &DDRC
#define SHIFTREGISTERDATADDPORT &DDRB
#define SHIFTREGISTERLATCHDDPORT &DDRB

#define SHIFTREGISTERCLKPIN 0
#define SHIFTREGISTERDATAPIN 1
#define SHIFTREGISTERLATCHPIN 2

#define BLUEWINPORT &PORTC
#define YELLOWWINPORT &PORTC

#define BLUEWINDDPORT &DDRC
#define YELLOWWINDDPORT &DDRC

#define BLUEWINREADREGISTER &PINC
#define YELLOWWINREADREGISTER &PINC

#define BLUEWINREADPIN PINC1
#define YELLOWWINREADPIN PINC2

#define BLUEWINPIN 1
#define YELLOWWINPIN 2

#define FIRSTSWITCHINTERRUPTPORT &PORTD
#define SECONDSWITCHINTERRUPTPORT &PORTD

#define FIRSTSWITCHINTERRUPTDDPORT &DDRD
#define SECONDSWITCHINTERRUPTDDPORT &DDRD

#define FIRSTSWITCHINTERRUPTPIN 2
#define SECONDSWITCHINTERRUPTPIN 3



void InitGameplay(void);
void CreateBoardStateArrays(void);
void PlayGame(uint8_t onePlayer, uint8_t goingFirst);
void DoTurn(uint8_t team, uint8_t humanPlayer);
uint8_t CheckForWin(uint8_t team);
uint8_t CheckForDraw(void);
void SetPinOnPort(volatile uint8_t* port, uint8_t pin, uint8_t on, uint8_t onShift);
void ResetShiftRegister(void);
void ResetBoards(void);
void SetBoardLocation(uint8_t isBlue, uint8_t square, uint8_t occupied);
void SetRegisters(void);
void ResetGameStuff(void);





#endif /* GAMEPLAYHANDLER_H_ */